spring.application.name=apiagendaweb

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5436/bd-agendaweb
spring.datasource.username=user-agendaweb
spring.datasource.password=pass-agendaweb
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect